### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by MateVaradi** [hakobayato/ldadf#1]
Hi! I am trying to use your model for my master thesis. When running the example you provided I am running into the following error message. Do you have any tips as to what is going wrong?

```
(base) C:\Users\m.varadi\Thesis\ldadf> python example.py -I

Select a constraint:
0)
1) ML("A","B")
2) CL("B", "C")
3) IL("B", "A")
4) ML("A", "B") | ML("A", "C")
5) IL("B", "A") & IL("C", "A")
6) ( ML("A", "B") | ML("A", "C") ) & CL("B", "C")
7) IL("B", "A") & IL("C", "A") & CL("B", "C")
8) ML("A", "B") & ML("A", "C")
9) ML("A", "B") & CL("B", "C")

Index> 0)
invalid literal for int() with base 10: '0)'

Select a constraint:
0)
1) ML("A","B")
2) CL("B", "C")
3) IL("B", "A")
4) ML("A", "B") | ML("A", "C")
5) IL("B", "A") & IL("C", "A")
6) ( ML("A", "B") | ML("A", "C") ) & CL("B", "C")
7) IL("B", "A") & IL("C", "A") & CL("B", "C")
8) ML("A", "B") & ML("A", "C")
9) ML("A", "B") & CL("B", "C")

Index> 2
= Parameters
dat_file: ./data/test.dat
lex_file: ./data/test.lex
cst_text: CL("B", "C")
eta: 100
seed: None
verbose: False

= Compile constraint links
python utils/compiler.py -c'CL("B", "C")' -l./data/test.lex -d./out/example/test.dnf
Traceback (most recent call last):
  File "utils/compiler.py", line 4, in <module>
    from parser import LinkParser, LinkParserException
ImportError: cannot import name 'LinkParser' from 'parser' (unknown location)

= Train LDADF with constraint links
The system cannot find the path specified.
./src/ldadf -n2 -m1000 -a1 -b0.01 -e100 -l10 -u5 -o./out/example/test -d./out/example/test.dnf ./data/test.dat
'.' is not recognized as an internal or external command,
operable program or batch file.

= Learned parameters
python utils/viewer.py -p./out/example/test.final -l./data/test.lex -d./out/example/test.dnf
Traceback (most recent call last):
  File "utils/viewer.py", line 182, in <module>
    out_file=args.out, verbose=args.verbose)
  File "utils/viewer.py", line 24, in __init__
    self.dnf.load(dnf_file, self.id2word)
  File "C:\Users\m.varadi\Thesis\ldadf\utils\dnf.py", line 30, in load
    with open(filename) as f:
FileNotFoundError: [Errno 2] No such file or directory: './out/example/test.dnf'

Select a constraint:
0)
1) ML("A","B")
2) CL("B", "C")
3) IL("B", "A")
4) ML("A", "B") | ML("A", "C")
5) IL("B", "A") & IL("C", "A")
6) ( ML("A", "B") | ML("A", "C") ) & CL("B", "C")
7) IL("B", "A") & IL("C", "A") & CL("B", "C")
8) ML("A", "B") & ML("A", "C")
9) ML("A", "B") & CL("B", "C")

Index>
```

**Comment by hakobayato** [comment]
Thanks for the comment. I have never checked my code in any windows environment, but the following modification might fix the problem. I confirmed it with MinGW+Anaconda.

- compiler.py
```
#from parser import LinkParser, LinkParserException
import imp
imp.load_source('parser', 'utils/parser.py')
from parser import LinkParser, LinkParserException
```
- example.py
```
        #cmd = 'python utils/compiler.py -c\'{}\' -l{} -d{}'.format(cst_text, lex_file, dnf_file)
        cmd = 'python utils/compiler.py -c\"{}\" -l{} -d{}'.format(cst_text.replace('"','\\\"'), lex_file, dnf_file)
...
    #if not os.path.exists('./src/ldadf'):
    #    os.system('cd src; make release')
    #cmd = './src/ldadf -n{} -m{} -a{} -b{} -e{} -l{} -u{} -o{}'.format(topic, step, alpha, beta, eta, loop, burn, out_pref)
    if not os.path.exists('src\\ldadf.exe'):
        os.system('cd src && mingw32-make')
    cmd = 'src\\ldadf.exe -n{} -m{} -a{} -b{} -e{} -l{} -u{} -o{}'.format(topic, step, alpha, beta, eta, loop, burn, out_pref)
```
